export const GET_STUDENTS = "GET_STUDENTS";

export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_ERROR = "GET_STUDENTS_ERROR";
export const ADD_STUDENTS = "ADD_STUDENTS";

export const ADD_STUDENTS_REQUEST = "ADD_STUDENTS_REQUEST";
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS";
export const ADD_STUDENTS_ERROR = "ADD_STUDENTS_ERROR";

export const ADD_LECTURE_REQUEST = "ADD_LECTURE_REQUEST"
export const ADD_LECTURE_SUCCESS = "ADD_LECTURE_SUCCESS"
export const ADD_LECTURE_ERROR = "ADD_LECTURE_ERROR"